version: '3'

services:
  mongo-db:
    image: bitnami/mongodb
    container_name: product_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USER: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: product_admin
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
